name: Artifacts Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::279113746415:role/Github
          aws-region: us-east-2
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: install deps
        run: pip install lambda-setuptools
      - name: Upload
        run: |
          python setup.py sdist ldist lupload --s3-bucket=${{secrets.S3BUCKET}}
        if: ${{ success() }}
